# -*- coding: utf-8 -*-
"""SVR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tigefWFXQBadKPeb9v_H9-ykEp3yR08U
"""

from google.colab import files
up=files.upload()

#step 1:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_csv('Position_Salaries.csv')
X=data.iloc[:,1:2].values
y=data.iloc[:,2:3].values
data.head()

#FEATURE SCALING
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
sc_y=StandardScaler()
X=sc_x.fit_transform(X)
y=sc_y.fit_transform(y)

#making model
from sklearn.svm import SVR
reg=SVR(kernel='rbf')
reg.fit(X,y)
y_pred=sc_y.inverse_transform(reg.predict(X))
print(y_pred)
print(sc_y.inverse_transform(y))

#plotting
import seaborn as sns
plt.scatter(sc_x.inverse_transform(X),sc_y.inverse_transform(y),color="blue")#actual
plt.plot(sc_x.inverse_transform(X),sc_y.inverse_transform(reg.predict(X)),color='green')#predicted
plt.show()